#!/usr/bin/env bash
# This script transfers a file from a client to a server using scp

# Check if all required parameters are provided
if [ $# -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assigning parameters to variables
path_to_file=$1
ip=$2
username=$3
path_to_ssh_key=$4

# Transfer file using scp with strict host key checking disabled
scp -o StrictHostKeyChecking=no -i "$path_to_ssh_key" "$path_to_file" "$username@$ip":~
