#!/usr/bin/env bash
# This script transfers a file from a client to a server using scp

# Check if all required parameters are provided
if [ $# -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assigning parameters to variables
path_to_file=some_page.html
ip=107.22.142.174
username=ubuntu
path_to_ssh_key=~/root/.ssh.school

# Transfer file using scp with strict host key checking disabled
scp -o StrictHostKeyChecking=no -i "$path_to_ssh_key" "$path_to_file" "$username@$ip":~
