#!/usr/bin/env bash
# Install Nginx on remote server and listen on port 80
# Install nginx package with -y option to automatically answer yes to prompts
sudo apt-get update
sudo apt-get install -y nginx

# Define the Nginx configuration
echo '
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        return 200 "Hello World!\n";
    }
}' > /etc/nginx/sites-available/default

# Restart Nginx without using systemctl
kill -s HUP $(pgrep nginx)

# Check if Nginx is running
if pgrep nginx > /dev/null; then
    echo "Nginx is running."
else
    echo "Nginx failed to start."
fi

# Check if Nginx serves a page with "Hello World!" content
curl -s localhost | grep "Hello World!"
