#!/usr/bin/env bash

# Update the package repository
sudo apt update

# Install HAProxy
sudo apt install -y haproxy

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<'EOF'
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    stats uri /haproxy?stats

    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 107.22.142.174:80 check
    server web-02 3.85.1.94:80 check
EOF

# Update the placeholder IP addresses with the actual IP addresses of web-01 and web-02
sudo sed -i 's/\[107.22.142.174\]/107.22.142.174/g' /etc/haproxy/haproxy.cfg
sudo sed -i 's/\[3.85.1.94\]/3.85.1.94/g' /etc/haproxy/haproxy.cfg

# Restart HAProxy to apply changes
sudo systemctl restart haproxy

# Enable HAProxy to start on boot
sudo systemctl enable haproxy

# Output success message
echo "HAProxy installed and configured successfully."
