#!/usr/bin/env bash
# PINGs an IP address

if [ $# -eq 0 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

ip_address=$1

echo "PING $ip_address ($ip_address) 56(84) bytes of data."

# Ping the IP address 5 times
ping -c 5 "$ip_address"

# Exit status of ping command
exit_status=$?

# Display statistics based on exit status
if [ $exit_status -eq 0 ]; then
    echo -e "\n--- $ip_address ping statistics ---"
    echo "5 packets transmitted, 5 received, 0% packet loss, time $(ping -c 5 -W 1 "$ip_address" | grep -oP "time \K[^ ]+" | awk "{print $1}")ms"
    echo "rtt min/avg/max/mdev = $(ping -c 5 "$ip_address" | tail -n 1 | grep -oP "(\d+\.\d+)/(\d+\.\d+)/(\d+\.\d+)/(\d+\.\d+)" | awk "{print $1 '/' $2 '/' $3 '/' $4}") ms"
else
    echo -e "\n--- $ip_address ping statistics ---"
    echo "5 packets transmitted, 0 received, 100% packet loss"
fi

