#!/usr/bin/env bash
# Display a list of currently running processes
# -a: Show processes for all users
# -x: Show processes without controlling TTY
# -u: User-oriented format
# --forest: show process hierachy
ps aux --forest