#!/usr/bin/env bash
# To stop a process without using kill
# ./4-to_infinity_and_beyond

# Find the PGID of the 4-to_infinity_and_beyond process
pgid=$(pgrep -f "4-to_infinity_and_beyond")

kill -s SIGINT -- "$pgid"