#!/usr/bin/env bash
# To stop a process without using kill
# Specify the process name
process_name="4-to_infinity_and_beyond"

# Use pkill to send the SIGTERM signal to the process
pkill -TERM -f "$process_name"

# Optionally, wait for the process to finish
wait