#!/usr/bin/env bash
# This script tells a fictional story based on /etc/passwd

while IFS=":" read -r username _ gid _ home shell; do
  echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $gid's place is protected by the passcode x, more info about the user here: $username"
done < /etc/passwd
