#!/usr/bin/env bash
# Pings localhost and facebook

# Backup /etc/hosts file
sudo cp /etc/hosts /etc/hosts.bak

# Create a temporary copy of hosts file
cp /etc/hosts ~/hosts.new

# Modify the temporary copy with sed
sed -i 's/127.0.0.1\(.*\)localhost/127.0.0.2\1localhost/' ~/hosts.new
sed -i 's/^.*facebook.com/8.8.8.8 facebook.com/' ~/hosts.new

# Copy the modified file back to /etc/hosts
sudo cp -f ~/hosts.new /etc/hosts

# Output success message
echo "Host configurations updated successfully."

# Show updated /etc/hosts file
echo "Updated /etc/hosts file:"
cat /etc/hosts
