#!/usr/bin/env bash
# This script configures Nginx to serve a Flask application and starts the Flask application with Gunicorn.

# Create the Nginx configuration file
sudo bash -c 'cat <<EOL > /etc/nginx/sites-available/4-app_server-nginx_config
server {
    listen 80;
    server_name 54.146.66.65;

    location /api/ {
        proxy_pass http://127.0.0.1:5002;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    #location /static {
    #    alias /path/to/your/static/files;
    #}
}
EOL'

# Enable the new Nginx configuration
sudo ln -s /etc/nginx/sites-available/4-app_server-nginx_config /etc/nginx/sites-enabled/

# Test the Nginx configuration for syntax errors
sudo nginx -t

# Reload Nginx to apply the new configuration
sudo systemctl reload nginx

# Start the Flask application with Gunicorn
