#!/usr/bin/env bash
# Connecting this public key to  server

# Define variables
private_key="~/.ssh/authorized_keys"
username="ubuntu"
server_ip="107.22.142.174"

# Use ssh with single-character flags to connect
ssh -i "$private_key" "$username"@"$server_ip"

